echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "Hello batch-24, We are learning git"
echo "Please complete your practicals on daily basis"
echo "wife : i want to travel "
echo "hi all we will do pratices on daily basic from today"
